Blog-Project/src/blog/urls.py
from django.urls import path
from .views import post_list, post_create, post_detail, post_update


app_name = "blog"
urlpatterns = [
    path("", post_list, name="list"),
    path("create/", post_create, name="create"),
    path("<str:slug>/", post_detail, name="detail"),
    path("<str:slug>/update/", post_update, name="update"),
]

Blog-Project/src/cblog/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Blog-Project/src/blog/models.py
from email.policy import default
from pyexpat import model
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


def user_directory_path(instance, filename):
    return 'blog/{0}/{1}'.format(instance.author.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    OPTIONS = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(
        upload_to=user_directory_path, default='arnold.jpg')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    publish_date = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default='d')
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

Blog-Project/src/blog/forms.py
from django import forms
from .models import Category, Post, Comment


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), empty_label='Select')

    class Meta:
        model = Post
        fields = (
            'title',
            'image',
            'content',
            'category',
            'status',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

Blog-Project/src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm

# Create your views here.


def post_list(request):
    qs = Post.objects.filter(status="p")
    context = {
        "object_list": qs
    }
    return render(request, "blog/post_list.html", context)


def post_create(request):
    # form = PostForm(request.POST or None, request.FILES or None)
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("blog:list")
    context = {
        'form': form
    }
    return render(request, "blog/post_create.html", context)


def post_detail(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    context = {
        'object': obj
    }
    return render(request, "blog/post_detail.html", context)


def post_update(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect("blog:list")

    context = {
        'object': obj,
        'form': form
    }
    return render(request, "blog/post_update.html", context)

Blog-Project/src/blog/templates/blog/post_create.html
{% extends 'base.html' %} {% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">POST</button>
</form>

{% endblock content %}

Blog-Project/src/blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block content %}
<h1>{{object.title}}</h1>
<img src="{{object.image.url}}" alt="" width="200px" height="200px" />
<p>{{object.content}}</p>

{% endblock content %}

Blog-Project/src/blog/templates/blog/post_list.html
{% extends 'base.html' %} {% block content %} {% for object in object_list %}
<a href="{% url 'blog:detail' object.slug%}">
  <h1>{{object.title}}</h1>
</a>
<img src="{{object.image.url}}" alt="" width="200px" height="200px" />
<p>{{object.content | truncatechars:20}}</p>
{% endfor %} {% endblock content %}

Blog-Project/src/blog/templates/blog/post_update.html
{% extends 'base.html' %} {% block content %}
<h2>Update {{object.title}}</h2>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Update</button>
</form>
{% endblock content %}

Blog-Project/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Clarusway <i class="fa fa-building-o" aria-hidden="true"></i></title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>